version: 2
models:
- name: stg_events
  description: ''
  columns:
  - name: event_id
    description: ''
    tests:
          - unique
          - not_null
- name: stg_users
  description: ''
  columns:
  - name: user_id
    description: ''
    tests:
          - unique
          - not_null
- name: stg_addresses
  description: ''
  columns:
  - name: address_id
    description: ''
    tests:
          - unique
          - not_null
- name: stg_orders
  description: ''
  columns:
  - name: order_id
    description: ''
    tests:
          - unique
          - not_null
  - name: status
    description: ''
    tests:
          - accepted_values:
              values: ['shipped', 'pending', 'preparing', 'delivered']
- name: stg_order_items
  description: "Model containing order basket information: product_id and quantity"
  columns:
    - name: quantity
      tests:
        - not_null
        - positive_values
- name: stg_products
  description: ''
  columns:
  - name: product_id
    description: ''
    tests:
          - unique
          - not_null
  - name: price
    description: ''
    tests:
          - not_null
          - positive_values
  - name: quantity
    description: ''
    tests:
          - not_null
- name: stg_promos
  description: ''
  columns:
  - name: id
    description: ''
  - name: promo_id
    description: ''
  - name: discount
    description: ''
  - name: status
    description: ''
